In [39]:
import pandas as pd
import json

In [40]:
coursesfile = open("coursesData.json")
coursesJson = json.loads(coursesfile.read())
coursesfile.close()

coursesMin = []
sectionsObj = []

for course in coursesJson:
	cid = course['course_id']

	sections_ids = ["TBA"] if course['sections']== [] else [ s['section_id'] for s in course['sections']]

	for s in course['sections']:
		meet0 = s["meetings"]
		meet =[]

		for m in meet0: 
			meet.append([ m['classtype'], m['days'], m['start_time'], m['end_time']]) 
		
		sectionsObj.append({
		"section_id": s['section_id'], 
		"meetings": meet ,
		"seats": s['seats'] 
		})	
	
	coreqs = course['relationships']['coreqs']
	prereqs = course['relationships']['prereqs']

	coursesMin.append({
	"id": str(course["course_id"]), 
	"name": str(course["name"]), 
	"desc": str(course["description"]),
	"dept_id": str(course["dept_id"]), 
	"credits": str(course["credits"]),
	"coreqs": str(coreqs),
	"prereqs": str(prereqs), 
	"section_ids": sections_ids,
	})


with open("coursesMin.json", "w") as f:
	json.dump(coursesMin, f)

with open("sections.json", "w") as f:
	json.dump(sectionsObj, f)

In [41]:
pd.read_json("coursesMin.json")

,id,name,desc,dept_id,credits,coreqs,prereqs,section_ids
0,AASP100,Introduction to African American Studies,Significant aspects of the history of African ...,AASP,3,None,None,"[AASP100-0101, AASP100-0201, AASP100-0301, AAS..."
1,AASP100H,Introduction to African American Studies,Significant aspects of the history of African ...,AASP,3,None,None,[AASP100H-0101]
2,AASP101,Public Policy and the Black Community,The impact of public policies on the black com...,AASP,3,None,None,[AASP101-0101]
3,AASP200,African Civilization,A survey of African civilizations from 4500 B....,AASP,3,None,None,"[AASP200-0101, AASP200-FC01]"
4,AASP202,Black Culture in the United States,The course examines important aspects of Afric...,AASP,3,None,None,"[AASP202-0101, AASP202-0102, AASP202-0103, AAS..."
...,...,...,...,...,...,...,...,...
4657,WMST699,Independent Study,None,WMST,1,None,None,[TBA]
4658,WMST709,Directed Independent Reading for Major Field Exam,None,WMST,1,None,None,[TBA]
4659,WMST799,Masters Thesis Research,None,WMST,1,None,None,[TBA]
4660,WMST898,Pre-Candidacy Research,None,WMST,1,None,None,[TBA]
4661,WMST899,Doctoral Dissertation Research,None,WMST,6,None,None,[TBA]

In [43]:
pd.read_json("sections.json")

         section_id                                           meetings  seats
0      AASP100-0101  [[, MWF, 10:00am, 10:50am], [, MWF, 10:00am, 1...     21
1      AASP100-0201  [[, MWF, 12:00pm, 12:50pm], [, MWF, 12:00pm, 1...     21
2      AASP100-0301  [[, TuTh, 9:30am, 10:45am], [, TuTh, 9:30am, 1...     21
3      AASP100-0401  [[, TuTh, 12:30pm, 1:45pm], [, TuTh, 12:30pm, ...     18
4      AASP100-0501  [[, TuTh, 11:00am, 12:15pm], [, TuTh, 11:00am,...     21
...             ...                                                ...    ...
8506  WMST498Y-0101  [[, TuTh, 2:00pm, 3:15pm], [, TuTh, 2:00pm, 3:...     20
8507   WMST601-0101     [[, W, 6:00pm, 8:30pm], [, W, 6:00pm, 8:30pm]]     12
8508   WMST618-0101                               [[, , , ], [, , , ]]      4
8509   WMST619-0101                               [[, , , ], [, , , ]]     10
8510   WMST628-0101                               [[, , , ], [, , , ]]     18

[8511 rows x 3 columns]